### ISSUE TITLE
Cannout mount container volumes

### ISSUE THREAD

**Issue by rhodius** [mkobit/docker-nifi#5]
I have tried to run the image by mounting the volumes to local folders on host such that I can persist data created by nifi. Each time nifi exits with a (0) status. After investigating I saw during an interactive session within the container that when these 'volumes' are mounted to local folders, they cannot be written to from within the container. The directory permissions appear as follows;

drwxr-xr-x 12 nifi nifi  4096 Mar 25 18:27 .
drwxr-xr-x  3 root root  4096 Mar  7 04:11 ..
-rw-r--r--  1 nifi nifi 62747 Feb 12 21:52 LICENSE
-rw-r--r--  1 nifi nifi 42391 Feb 20 14:43 NOTICE
-rw-r--r--  1 nifi nifi  4549 Oct 16 22:48 README
drwxr-xr-x  2 nifi nifi  4096 Mar  7 04:11 bin
drwxr-xr-x  2 nifi nifi  4096 Mar 25 20:12 conf
drwxrwxr-x  2  503  504  4096 Mar 25 18:51 content_repository
drwxr-xr-x  2 nifi nifi  4096 Mar 25 20:12 data
drwxrwxr-x  2  503  504  4096 Mar 25 18:50 database_repository
drwxr-xr-x  3 nifi nifi  4096 Mar  7 04:11 docs
drwxr-xr-x  3 nifi nifi  4096 Mar 25 20:12 etc
drwxrwxr-x  2  503  504  4096 Mar 25 18:50 flowfile_repository
drwxr-xr-x  3 nifi nifi  4096 Mar  7 04:11 lib
drwxrwxr-x  2  503  504  4096 Mar 25 18:50 provenance_repository

I am able to mount other docker images to local folders without such issues. I cannot identify the problem.

The docker run command is as follows;

docker run -i -t \
--name nifi-container \
-p 8080:8080 \
-p 80:8081 \
--volume=/home/ahassan/DEV/data/nifi/database_repository:/opt/nifi/database_repository \
--volume=/home/ahassan/DEV/data/nifi/flowfile_repository:/opt/nifi/flowfile_repository \
--volume=/home/ahassan/DEV/data/nifi/content_repository:/opt/nifi/content_repository \
--volume=/home/ahassan/DEV/data/nifi/provenance_repository:/opt/nifi/provenance_repository \
mkobit/docker-nifi:0.5.1-openjdk-7 \
/bin/bash

**Comment by mkobit** [comment]
Thanks for reporting. 

I am able to reproduce this locally on my Mac as well. I followed the similar repro steps you provided, as well as just trying to `touch` a file inside of containers volume and got the same permission error. 

```
mkdir {database_repository,flowfile_repository,content_repository,provenance_repository}
docker run -i -t \
  --name nifi-container \
  -p 8080:8080 \
  -p 8081:8081 \
  -v `pwd`/database_repository:/opt/nifi/database_repository \
  -v `pwd`/flowfile_repository:/opt/nifi/flowfile_repository \
  -v `pwd`/content_repository:/opt/nifi/content_repository \
  -v `pwd`/provenance_repository:/opt/nifi/provenance_repository \
  mkobit/nifi:0.5.1-openjdk-7
```

Error logs:
```
2016-03-28 13:46:20,134 ERROR [main] org.apache.nifi.NiFi Failure to launch NiFi due to java.util.ServiceConfigurationError: org.apache.nifi.controller.repository.FlowFileSwapManager: Provider org.apache.nifi.controller.FileSystemSwapManager could not be instantiated
java.util.ServiceConfigurationError: org.apache.nifi.controller.repository.FlowFileSwapManager: Provider org.apache.nifi.controller.FileSystemSwapManager could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:224) ~[na:1.7.0_95]
        at java.util.ServiceLoader.access$100(ServiceLoader.java:181) ~[na:1.7.0_95]
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:377) ~[na:1.7.0_95]
        at java.util.ServiceLoader$1.next(ServiceLoader.java:445) ~[na:1.7.0_95]
        at org.apache.nifi.nar.ExtensionManager.loadExtensions(ExtensionManager.java:107) ~[nifi-nar-utils-0.5.1.jar:0.5.1]
        at org.apache.nifi.nar.ExtensionManager.discoverExtensions(ExtensionManager.java:88) ~[nifi-nar-utils-0.5.1.jar:0.5.1]
        at org.apache.nifi.NiFi.<init>(NiFi.java:120) ~[nifi-runtime-0.5.1.jar:0.5.1]
        at org.apache.nifi.NiFi.main(NiFi.java:227) ~[nifi-runtime-0.5.1.jar:0.5.1]
Caused by: java.lang.RuntimeException: Cannot create Swap Storage directory /opt/nifi/./flowfile_repository/swap
        at org.apache.nifi.controller.FileSystemSwapManager.<init>(FileSystemSwapManager.java:91) ~[nifi-framework-core-0.5.1.jar:0.5.1]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_95]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_95]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_95]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_95]
        at java.lang.Class.newInstance(Class.java:383) ~[na:1.7.0_95]
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:373) ~[na:1.7.0_95]
        ... 5 common frames omitted
2016-03-28 13:46:20,134 INFO [Thread-1] org.apache.nifi.NiFi Initiating shutdown of Jetty web server...
2016-03-28 13:46:20,135 INFO [Thread-1] org.apache.nifi.NiFi Jetty web server shutdown completed (nicely or otherwise).
...
java.util.ServiceConfigurationError: org.apache.nifi.controller.repository.ContentRepository: Provider org.apache.nifi.controller.repository.FileSystemRepository could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:224) ~[na:1.7.0_95]
        at java.util.ServiceLoader.access$100(ServiceLoader.java:181) ~[na:1.7.0_95]
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:377) ~[na:1.7.0_95]
        at java.util.ServiceLoader$1.next(ServiceLoader.java:445) ~[na:1.7.0_95]
        at org.apache.nifi.nar.ExtensionManager.loadExtensions(ExtensionManager.java:107) ~[nifi-nar-utils-0.5.1.jar:0.5.1]
        at org.apache.nifi.nar.ExtensionManager.discoverExtensions(ExtensionManager.java:88) ~[nifi-nar-utils-0.5.1.jar:0.5.1]
        at org.apache.nifi.NiFi.<init>(NiFi.java:120) ~[nifi-runtime-0.5.1.jar:0.5.1]
        at org.apache.nifi.NiFi.main(NiFi.java:227) ~[nifi-runtime-0.5.1.jar:0.5.1]
Caused by: java.nio.file.AccessDeniedException: /opt/nifi/content_repository/0
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[na:1.7.0_95]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.7.0_95]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.7.0_95]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:383) ~[na:1.7.0_95]
        at java.nio.file.Files.createDirectory(Files.java:630) ~[na:1.7.0_95]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:734) ~[na:1.7.0_95]
        at java.nio.file.Files.createDirectories(Files.java:720) ~[na:1.7.0_95]
        at org.apache.nifi.controller.repository.FileSystemRepository.initializeRepository(FileSystemRepository.java:288) ~[nifi-framework-core-0.5.1.jar:0.5.1]
        at org.apache.nifi.controller.repository.FileSystemRepository.<init>(FileSystemRepository.java:212) ~[nifi-framework-core-0.5.1.jar:0.5.1]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_95]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_95]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_95]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_95]
        at java.lang.Class.newInstance(Class.java:383) ~[na:1.7.0_95]
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:373) ~[na:1.7.0_95]
        ... 5 common frames omitted
```

I also have a feeling there is also a bug in the NiFi launcher script that causes the (0) exit code even when it fails to start up several times.

I'll hopefully get a chance to dive into this more this week.

**Comment by mkobit** [comment]
@rhodius Could you provide any additional information around your working environment?

- Are you using `boot2docker` or `docker-machine`?
- What OS are you using?
- An example of another container that you are using that this works with?

**Comment by brosander** [comment]
This is a more generic docker issue around how linux file permissions are handled.

The nifi user has a uid of 999 and a gid of 1000 at least in the latest image, you can check for whatever version you want by running;
```
docker run -it --rm -p 8080-8081:8080-8081 mkobit/nifi id
```

If your local uid and gid are different, (can be determined by running same command locally) [you're gonna have a bad time...](https://github.com/docker/docker/issues/7198)

You can change nifi's uid and gid with the follwoing workaround (You'll want to replace the image I used with the one you want and the NEW_UID and NEW_GID with the values you get when you run the id command on the host):
```
docker run --cidfile=cidfile -it -u root -p 8080-8081:8080-8081 mkobit/nifi \
/bin/bash -c 'NEW_UID=1000; NEW_GID=1000; OLD_UID=`id -u nifi`; OLD_GID=`id -g nifi`; usermod -u $NEW_UID nifi; groupmod -g $NEW_GID nifi; find / -user $OLD_UID -exec chown -h $NEW_UID {} \; 2>/dev/null; find / -group $OLD_GID -exec chgrp -h $NEW_GID {} \; 2>/dev/null; usermod -g $NEW_GID nifi' \
  && docker commit "`cat cidfile`" > imagefile \
  && rm cidfile \
  && docker tag "`cat imagefile`" my-volume-friendly-nifi-image \
  && rm imagefile
```
The above command is adapted from http://askubuntu.com/questions/312919/how-to-change-user-gid-and-uid-in-ubuntu-13-04#answer-312925

Unfortunately, you will now need to specify the user and command as my workaround stomps them:
```
docker run -i -t --rm \
  -u nifi \
  --name nifi-container \
  -p 8080:8080 \
  -p 8081:8081 \
  -v `pwd`/database_repository:/opt/nifi/database_repository \
  -v `pwd`/flowfile_repository:/opt/nifi/flowfile_repository \
  -v `pwd`/content_repository:/opt/nifi/content_repository \
  -v `pwd`/provenance_repository:/opt/nifi/provenance_repository \
  my-volume-friendly-nifi-image \
  bin/nifi.sh run
```

**Comment by mkobit** [comment]
@brosander Thanks for the detailed write-up. I suspected it was something along those lines, but I couldn't really nail it down to something specific.

One option that might be useful (I think) would be to make the userId, user name, groupId, and group name be configurable at build time with the `ARG` instruction. I saw something similar with the _Dockerfile_ in the [Jenkins project](https://github.com/jenkinsci/docker/blob/d014524ce333b9e8c2f647756f52c4a31329e3a4/Dockerfile).

It sounds like, to me, there is not really a good way to deal with this.

**Comment by brosander** [comment]
@mkobit I'm actually trying to build that into the dockerfile right now but am running into a strange issue where the [volumes' permissions just don't stick](http://stackoverflow.com/questions/26145351/why-doesnt-chown-work-in-dockerfile)

**Comment by rhodius** [comment]
I am sorry I did not get time to send my workaround for this problem. I
found the answer when I stumbled upon the official docker file for apache
cassandra. If you inspect the docker file, the UID and GID are explicitly
assigned during image creation. I used this technique to derive an image
based on your image with the UID and GID set manually to match the host and
that solved all the issues.


* # explicitly set user/group IDs *RUN groupadd -r cassandra --gid=999 &&
useradd -r -g cassandra --uid=999 cassandra



*# explicitly set user/group IDs --- my version*
RUN usermod -u 503 nifi \
   && groupmod -g 504 nifi \
   && usermod -g 504 nifi \
   && mkdir -p $NIFI_HOME/etc/hadoop/conf \
   && mkdir $NIFI_HOME/data \
   && chown -R nifi:nifi /opt/nifi \

Unrelated to this problem, I would suggest to create additional base
volumes for sharing configuration information that nifi needs to talk to
3rd parties e.g. in my case I needed to point data processors to hadoop
config files located on the host. I am currently using this modified image
without any issues. I do have some issues regarding data persistence i.e.
between 2 containers based on the same image, using the same local
directories - But perhaps its because I'm a Nifi newbie :)

**Comment by mkobit** [comment]
Going to close this. I've added the ability to specify a different user and group at build time.

I haven't found a good workaround for this over the last few months when trying to share host volumes with the container. Using `--group-add` helps, but if you run the container with a different user or group than what is specified in the container, you're going to have a bad tone (I'm seeing thisa lot with some of the Jenkins work I have been doing).

**Comment by andhdo** [comment]
An alternative, could be add user root to the docker-compose file
`  nifi:
    image: mkobit/nifi:1.1.0-openjdk-8
    user: root
    container_name: nifi
    hostname: nifi
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - NIFI_HOME=/opt/nifi
      - LOCAL_HOME=~/andje-xnifi-cfg
    volumes:
      - ./nifi/nifi-cfg/conf:/opt/nifi/conf 
`

**Comment by ericchaves** [comment]
Could the use of ONBUILD ARGS help with this issue allowing the UID/GID to be overridden in child images?
something like this:
```
ONBUILD ARG NIFI_UID
ONBUILD ARG NIFI_GID
ONBUILD ENV $NIFI_UID ${NIFI_UID:-1000}
ONBUILD ENV $NIFI_GID ${NIFI_GID:-1000}
...
RUN set -x ... \
    && groupadd -g $NIFI_GID nifi \
    && useradd -u $NIFI_UID -r -g nifi nifi \
```
than those who wish to align UID/GID between host and container could build child images using build args to set it.

**Comment by mkobit** [comment]
It is possible that could make things easier for consumers. You could also modify the `entrypoint` to do all some of that work so you don't have to pay layer cost but may have to do some other steps with permissions in the repository directories.

Have you looked at the [official NiFi image](https://hub.docker.com/r/apache/nifi/) to see if that provides what you need?
