### ISSUE TITLE
0.6.1-openjdk-9 image doesn't work

### ISSUE THREAD

**Issue by ivan-m** [mkobit/docker-nifi#6]
If I try and use the `0.6.1-openjdk-9` tag for the Docker image, then trying to access NiFi via the browser results in the following error message appearing instead of NiFi:

```
HTTP ERROR 500

Problem accessing /nifi/. Reason:

    Server Error

Caused by:

org.apache.jasper.JasperException: PWC6033: Error in Javac compilation for JSP

PWC6199: Generated servlet error:
The type java.util.List cannot be resolved. It is indirectly referenced from required .class files

PWC6199: Generated servlet error:
The type java.lang.Exception cannot be resolved. It is indirectly referenced from required .class files

PWC6199: Generated servlet error:
The type java.lang.Throwable cannot be resolved. It is indirectly referenced from required .class files

PWC6199: Generated servlet error:
The type java.util.Enumeration cannot be resolved. It is indirectly referenced from required .class files

PWC6199: Generated servlet error:
The type java.io.IOException cannot be resolved. It is indirectly referenced from required .class files

PWC6199: Generated servlet error:
The type java.lang.String cannot be resolved. It is indirectly referenced from required .class files

PWC6199: Generated servlet error:
The hierarchy of the type canvas_jsp is inconsistent

PWC6199: Generated servlet error:
The type canvas_jsp must implement the inherited abstract method JspSourceDependent.getDependants()

PWC6199: Generated servlet error:
java.util.List cannot be resolved to a type

PWC6199: Generated servlet error:
String cannot be resolved to a type

PWC6199: Generated servlet error:
java.util.List cannot be resolved to a type

PWC6199: Generated servlet error:
String cannot be resolved to a type

PWC6199: Generated servlet error:
_jspx_dependants cannot be resolved to a variable

PWC6199: Generated servlet error:
java.io.IOException cannot be resolved to a type

PWC6199: Generated servlet error:
No exception of type ServletException can be thrown; an exception type must be a subclass of Throwable

PWC6199: Generated servlet error:
Object cannot be resolved to a type

PWC6199: Generated servlet error:
The method setContentType(String) from the type ServletResponse refers to the missing type String

PWC6199: Generated servlet error:
The method getPageContext(Servlet, ServletRequest, ServletResponse, String, boolean, int, boolean) from the type JspFactory refers to the missing type String

PWC6199: Generated servlet error:
The method getAttribute(String) from the type ServletContext refers to the missing type Object

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The type java.io.Writer cannot be resolved. It is indirectly referenced from required .class files

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 16 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 76 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method include(ServletRequest, ServletResponse, String, JspWriter, boolean) from the type JspRuntimeLibrary refers to the missing type String

PWC6197: An error occurred at line: 76 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 76 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 77 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method include(ServletRequest, ServletResponse, String, JspWriter, boolean) from the type JspRuntimeLibrary refers to the missing type String

PWC6197: An error occurred at line: 77 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 77 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 78 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method include(ServletRequest, ServletResponse, String, JspWriter, boolean) from the type JspRuntimeLibrary refers to the missing type String

PWC6197: An error occurred at line: 78 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 78 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 79 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method include(ServletRequest, ServletResponse, String, JspWriter, boolean) from the type JspRuntimeLibrary refers to the missing type String

PWC6197: An error occurred at line: 79 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 79 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 80 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method include(ServletRequest, ServletResponse, String, JspWriter, boolean) from the type JspRuntimeLibrary refers to the missing type String

PWC6197: An error occurred at line: 80 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 80 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 81 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method include(ServletRequest, ServletResponse, String, JspWriter, boolean) from the type JspRuntimeLibrary refers to the missing type String

PWC6197: An error occurred at line: 81 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 81 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method write(String) is undefined for the type JspWriter

PWC6197: An error occurred at line: 82 in the jsp file: /WEB-INF/pages/canvas.jsp
PWC6199: Generated servlet error:
The method include(ServletRequest, ServletResponse, String, JspWriter, boolean) from the type JspRuntimeLibrary refers to the missing type String


	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:129)
	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:299)
	at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:392)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:453)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:625)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:375)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:191)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:72)
	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:587)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.apache.nifi.web.filter.IeEdgeHeader.doFilter(IeEdgeHeader.java:45)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(java.base@9-internal/Thread.java:804)

Powered by Jetty:// 
```

Using 0.6.1-openjdk-7 works though, so it's not a general problem with 0.6.1 (I stopped testing after that point).

**Comment by mkobit** [comment]
Thanks for reporting. I also see the same thing now when rebuilding it locally. 0.6.1-openjdk-8 and 0.6.1-oracle-java8 both seem to work correctly. I haven't spent much time diving into the Java 9 stuff, but figured I would publish it for others to test with.

I doubt I will spend the time to try and fix this. It could just be because of some kind of incompatibilities or the JDK that I am using as the base is not bundling everything, but I don't think I am going to dive into it too much.

**Comment by ivan-m** [comment]
Fair enough; at least this way I know it's not just me and it's recorded if anyone else finds it.

**Comment by mkobit** [comment]
I'll take a closer look with the next release before publishing.

**Comment by mkobit** [comment]
Closing this. Not going to publish anymore Java 9 images (for now)
